import Head from "next/head";
import Header from "../components/Header";

export async function getStaticProps() {
  const response = await fetch(`https://restcountries.com/v3.1/all`);
  const data = await response.json();

  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {/* {data &&
        data.map((country) => {
          return (
            <div key={country.name.common}>
              <h2>{country.name.common}</h2>
              <img src={country.flags.png} alt={country.name.common} />
            </div>
          );
        })} */}
    </div>
  );
}
