import Card from "../components/Card";
import Head from "next/head";
import { QUERIES } from "../constants";
import Search from "../components/Search";
import Select from "../components/Select";
import styled from "styled-components";

export async function getStaticProps() {
  const response = await fetch(`https://restcountries.com/v3.1/all`);
  const data = await response.json();

  const isUnMember = data.filter((country) => country.unMember === true);

  const partialData = isUnMember.map(
    ({ name, flags, population, region, capital, flag }) => {
      return {
        id: flag,
        name: name.common,
        flags,
        population,
        region,
        capital: capital?.[0],
        flag,
      };
    }
  );

  return {
    props: {
      data: partialData,
    },
  };
}

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Search />
      <Select />

      <Main>
        {data &&
          data.map((country) => <Card key={country.name} data={country} />)}
      </Main>
    </>
  );
}

const Main = styled.main`
  --min-column-width: min(320px, 100%);

  @media ${QUERIES.tabletAndUp} {
    display: grid;
    grid-template-columns: repeat(
      auto-fill,
      minmax(var(--min-column-width), 1fr)
    );
    grid-gap: 1rem;
    padding-inline: 5rem;
  }
`;
