import Head from "next/head";
import Header from "../components/Header";
import Search from "../components/Search";

export async function getStaticProps() {
  const response = await fetch(`https://restcountries.com/v3.1/all`);
  const data = await response.json();

  const isUnMember = data.filter((country) => country.unMember === true);

  console.log(isUnMember.length);

  const partialData = isUnMember.map(
    ({ name, flags, population, region, capital, flag }) => {
      return {
        name: name.official,
        flags,
        population,
        region,
        capital: capital?.[0],
        flag,
      };
    }
  );

  return {
    props: {
      data: partialData,
    },
  };
}

export default function Home({ data }) {
  // console.log({ data });
  return (
    <div>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Search />

      {/* {data &&
        data.map(({ name, flag }) => {
          return (
            <div key={name}>
              <p>{flag}</p>
            </div>
          );
        })} */}
    </div>
  );
}
